# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/spotify_net',
                'doc_host': 'https://drewtray.github.io',
                'git_url': 'https://github.com/drewtray/spotify_net',
                'lib_path': 'spotify_net'},
  'syms': {'spotify_net.core': {'spotify_net.core.foo': ('core.html#foo', 'spotify_net/core.py')}}}
