# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"cred": "retrieve_public.ipynb",
         "get_tracks": "00_retrieve_spot.ipynb",
         "track_reduce": "00_retrieve_spot.ipynb",
         "update": "00_retrieve_spot.ipynb",
         "last_cred": "01_retrieve_last.ipynb",
         "last_get": "01_retrieve_last.ipynb",
         "last_format": "01_retrieve_last.ipynb",
         "load_s3": "03_hit_endpoint.ipynb",
         "merge_frame": "02_prepModel.ipynb",
         "dummies_and_scale": "02_prepModel.ipynb",
         "full_frame": "02_prepModel.ipynb",
         "prep_frame": "03_hit_endpoint.ipynb",
         "make_request": "03_hit_endpoint.ipynb",
         "p_dict": "03_hit_endpoint.ipynb",
         "add_tracks": "03_hit_endpoint.ipynb",
         "delete_tracks": "03_hit_endpoint.ipynb",
         "handler": "lambda.ipynb"}

modules = ["retrieve_spot_00.py",
           "retrieve_last_01.py",
           "prepModel_02.py",
           "hit_endpoint_03.py",
           "lambda.py",
           "retrieve_public.py"]

doc_url = "https://drewtray.github.io/spotify_net/"

git_url = "https://github.com/drewtray/spotify_net/tree/master/"

def custom_doc_links(name): return None
