name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write # This is required for requesting the JWT

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::569206664605:role/github-actions-secrets
          aws-region: us-east-2
      - uses: fastai/workflows/quarto-ghp@master
