name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::569206664605:role/github-actions-secrets
          aws-region: us-east-2
      - uses: fastai/workflows/nbdev-ci@master
